# /etc/samba/smb.conf 
[iPhoneShare]
   path = /home/jet/iPhone
   writable = yes
   guest ok = no
   valid users = jet
   # Apple-specific fixes for better performance/permissions
   vfs objects = catia fruit streams_xattr
   fruit:metadata = netatalk
   fruit:posix_rename = yes
