; Non Mono for Nerd Icons
; Usage T{font-$+1}
font-7 = "JetBrainsMono Nerd Font:style=Regular:size=8;4"
font-8 = "JetBrainsMono Nerd Font:style=Regular:size=8;3"
font-9 = "JetBrainsMono Nerd Font:style=Regular:size=8;3.8"
font-10 = "JetBrainsMono Nerd Font:style=Regular:size=10;2"
font-11 = "JetBrainsMono Nerd Font:style=Regular:size=10;2"
font-12 = "Noto Color Emoji:scale=10;2"
